### ISSUE TITLE
pointerIndex out of range exception

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gestures-android#17]
When testing out the library `IllegalArgumenntException` was thrown:
```
java.lang.IllegalArgumentException: pointerIndex out of range
    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
    at android.view.MotionEvent.getX(MotionEvent.java:2072)
    at com.mapbox.android.gestures.MultiFingerGesture.calculateDistances(MultiFingerGesture.java:166)
    at com.mapbox.android.gestures.MultiFingerGesture.analyzeEvent(MultiFingerGesture.java:71)
    at com.mapbox.android.gestures.ProgressiveGesture.analyzeEvent(ProgressiveGesture.java:47)
    at com.mapbox.android.gestures.MoveGestureDetector.analyzeEvent(MoveGestureDetector.java:132)
    at com.mapbox.android.gestures.BaseGesture.analyze(BaseGesture.java:56)
    at com.mapbox.android.gestures.BaseGesture.onTouchEvent(BaseGesture.java:34)
    at com.mapbox.android.gestures.AndroidGesturesManager.onTouchEvent(AndroidGesturesManager.java:130)
    at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:193)
```

**Comment by LukasPaczos** [comment]
This should be fixed with https://github.com/mapbox/mapbox-gestures-android/pull/16/commits/edc190b595c7a7c1207476a7d68a0c8d11001d69 that's a part of https://github.com/mapbox/mapbox-gestures-android/pull/16.
