### ISSUE TITLE
Single tap gesture crash

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gestures-android#38]
While working on mapbox/mapbox-navigation-android#697 found 👇

![singletapgestureissue](https://user-images.githubusercontent.com/1668582/38439627-a302ec34-39de-11e8-869b-257ab829a313.gif)

```
04-06 20:58:27.624 25800-25800/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.mapbox.services.android.navigation.testapp, PID: 25800
                                                   java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapbox.mapboxsdk.maps.MapboxMap$OnMapClickListener.onMapClick(com.mapbox.mapboxsdk.geometry.LatLng)' on a null object reference
                                                       at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapClickListeners(MapGestureDetector.java:913)
                                                       at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:344)
                                                       at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:81)
                                                       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Steps to reproduce:

1. Navigation test app (`dan-maps-3.0` branch in https://github.com/mapbox/mapbox-navigation-android/)
2. Open `Mock Navigation` activity
3. Tap map to place waypoint
4. Press the `START ROUTE` button
5. Tap map (single tap)
6. 💥

cc @LukasPaczos @tobrun @danesfeder

**Comment by LukasPaczos** [comment]
Thanks for flagging this one @Guardiola31337! Issue not related to the gestures library, though. Closing in favor of https://github.com/mapbox/mapbox-navigation-android/issues/837 and https://github.com/mapbox/mapbox-gl-native/issues/11628.
